[Flags]
public enum Daikhan.PlayFlags {
    VIDEO,
    AUDIO,
    SUBTITLES,
    VISUALISATION,
    SOFTWARE_VOLUME,
    NATIVE_AUDIO_ONLY,
    NATIVE_VIDEO_ONLY,
    PROGRESSIVE_DOWNLOADING,
    BUFFER_PARSED_DATA,
    DEINTERLACE,
    SOFTWARE_COLORBALANCE,
    FORCE_APPLY_FILTERS,
    FORCE_SOFTWARE_DECODERS,
}